- op: replace
  path: /spec/git/push/branch
  value: master
- op: replace
  path: /spec/update/path
  value: ./manifests/react-flight-tracker/overlays/prod
- op: replace
  path: /spec/sourceRef/name
  value: react-flight-tracker-prod