- op: replace
  path: /spec/git/push/branch
  value: develop
- op: replace
  path: /spec/update/path
  value: ./manifests/react-flight-tracker/overlays/dev
- op: replace
  path: /spec/sourceRef/name
  value: react-flight-tracker-dev