apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: react-flight-tracker
resources:
  - namespace.yaml
  - image-automation.yaml
  - image-policy.yaml
  - image-repository.yaml
  - react-flight-tracker-deployment.yaml
  - react-flight-tracker-service.yaml
  - react-flight-tracker-ingress.yaml
